---
Description: SSM document that checks Instance via inspec and publishes results to AWS SSM
AWSTemplateFormatVersion: "2010-09-09"


Resources:
  PasswordExpiryInstancesAssociation:
    Type: AWS::SSM::Association
    Properties:
      Name: !Ref PasswordExpirySSMDocument
      AssociationName: "PasswordExpiryInstancesAssociation"
      ScheduleExpression: "at(2021-05-17T08:20:00)"
      ApplyOnlyAtCronInterval: true
      Targets:
      - Key: tag:OS
        Values: 
        - Linux
  
  PasswordExpirySSMDocument:
    Type: AWS::SSM::Document
    Properties:
      Name: "PasswordExpiryAlertDocument"
      DocumentType: "Command"
      Content:
        schemaVersion: '2.2'
        mainSteps:
        - action: aws:downloadContent
          name: downloadContent
          inputs:
            sourceType: "S3"
            sourceInfo: "{\"path\": \"https://s3.amazonaws.com/acm-lambda-code-bucket/password_expiry.py\"}"
            destinationPath: "/opt/pythonscripts"
        - precondition:
            StringEquals:
            - platformType
            - Linux
          action: aws:runShellScript
          name: runInSpecLinux
          inputs:
            runCommand:
              - "#!/bin/bash"
              - "sudo chmod +x /opt/pythonscripts/password_expiry.py"
              - "(sudo crontab -l; echo '35 8 * * * python /opt/pythonscripts/password_expiry.py' ) | crontab -"
              